# Generated by Django 2.2.16 on 2020-09-18 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABC_Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=2)),
                ('web_interface', models.TextField(default='google.com')),
                ('vanessa_answ', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_module_code', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=200)),
                ('module_code', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
            ],
        ),
    ]
