# Generated by Django 2.2.16 on 2020-09-18 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc_modules',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_answers',
            name='id',
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='code_abc_modules',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user_answers',
            name='code_keys',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
