# Generated by Django 2.2.16 on 2020-09-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20200918_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_modules',
            name='code_abc_modules',
            field=models.UUIDField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_answers',
            name='code_keys',
            field=models.UUIDField(default=0, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
