# Generated by Django 2.2.16 on 2020-09-22 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20200922_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc_modules',
            name='next_module_code',
        ),
        migrations.RemoveField(
            model_name='abc_modules',
            name='vanessa_answ',
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='Vanessa_answer_word',
            field=models.BooleanField(default=False, verbose_name='Использовать слова пользователя в ответе'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='module_level',
            field=models.IntegerField(default=0, verbose_name='Уровень модуля'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='module_used',
            field=models.BooleanField(default=True, verbose_name='Модуль используется Ванессой'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='previous_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbot.ABC_Modules'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='url_address',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='vanessa_answer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ответ Ванессы'),
        ),
        migrations.AddField(
            model_name='abc_modules',
            name='vanessa_question',
            field=models.CharField(default='', max_length=200, verbose_name='Вопрос Ванессы'),
        ),
        migrations.AlterField(
            model_name='abc_modules',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания модуля'),
        ),
        migrations.AlterField(
            model_name='abc_modules',
            name='module_type',
            field=models.CharField(max_length=1, verbose_name='Тип модуля'),
        ),
        migrations.AlterField(
            model_name='abc_modules',
            name='web_interface',
            field=models.CharField(blank=True, default='Интерфейс', max_length=200, verbose_name='Интерфейс'),
        ),
    ]
