# Generated by Django 2.2.16 on 2020-09-22 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200922_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answers',
            name='title_block',
        ),
        migrations.RemoveField(
            model_name='user_answers',
            name='weight',
        ),
        migrations.AddField(
            model_name='user_answers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='user_answers',
            name='keyword_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес(важность) слова'),
        ),
        migrations.AlterField(
            model_name='user_answers',
            name='keyword',
            field=models.CharField(max_length=30, verbose_name=' Ключевое слово'),
        ),
        migrations.AlterField(
            model_name='user_answers',
            name='module_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chatbot.ABC_Modules'),
        ),
    ]
