# Generated by Django 2.2.16 on 2020-09-22 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20200922_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_modules',
            name='code_abc_modules',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
