# Generated by Django 2.2.16 on 2020-09-23 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20200922_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerWord',
            fields=[
                ('code_keys', models.UUIDField(default=0, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('keyword', models.CharField(blank=True, max_length=30, verbose_name=' Ключевое слово')),
                ('keyword_weight', models.FloatField(blank=True, null=True, verbose_name='Вес(важность) слова')),
                ('next_module_number', models.IntegerField(default=0, verbose_name='Номер следующего модуля')),
                ('vanessa_answer', models.CharField(blank=True, max_length=200, verbose_name='Ответ Ванессы')),
                ('url_address', models.URLField(blank=True, null=True, verbose_name='url ответа')),
            ],
        ),
        migrations.CreateModel(
            name='VanessaModule',
            fields=[
                ('code_abc_modules', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('module_type', models.CharField(max_length=1, verbose_name='Тип')),
                ('module_number', models.IntegerField(default=0, verbose_name='Номер')),
                ('module_used', models.BooleanField(default=True, verbose_name='Используется')),
                ('vanessa_question', models.CharField(max_length=200, verbose_name='Вопрос Ванессы')),
                ('Vanessa_answer_word', models.BooleanField(default=False, verbose_name='Использовать слова пользователя в ответе')),
                ('vanessa_answer', models.CharField(blank=True, max_length=200, verbose_name='Ответ Ванессы')),
                ('url_address', models.URLField(blank=True, null=True, verbose_name='url ответа')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_answers',
            name='module_code',
        ),
        migrations.DeleteModel(
            name='ABC_Modules',
        ),
        migrations.DeleteModel(
            name='User_Answers',
        ),
        migrations.AddField(
            model_name='useranswerword',
            name='module_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chatbot.VanessaModule'),
        ),
    ]
